"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestPolyglotricMicroServices,
	#superclass : #PackageManifest,
	#category : #'PolyglotricMicroServices-Manifest'
}

{ #category : #'code-critics' }
ManifestPolyglotricMicroServices class >> ruleBadMessageRule2V1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#PolyglotricMicroServices)) #'2020-07-03T13:38:15.731109-04:00') )
]
